name: Deploy to Heroku
on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}  # Defined in the repository Settings > Secrets
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: "speedway-trials-2021" #Must be unique in Heroku
          usedocker: true